/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:8fee909ee279cc1c5e3c72ebbfd6c3e2:521017297cf7b7e5841d7b0b4af1528f:da1f8de83c34907d12d357ddd091d34d$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class vampsassets
	{
		public const string Backgrounds_forest = "backgrounds/forest";
		public const string Butterflyrookfly_butterrook1 = "butterflyrookfly/butterrook1";
		public const string Butterflyrookfly_butterrook10 = "butterflyrookfly/butterrook10";
		public const string Butterflyrookfly_butterrook11 = "butterflyrookfly/butterrook11";
		public const string Butterflyrookfly_butterrook12 = "butterflyrookfly/butterrook12";
		public const string Butterflyrookfly_butterrook13 = "butterflyrookfly/butterrook13";
		public const string Butterflyrookfly_butterrook2 = "butterflyrookfly/butterrook2";
		public const string Butterflyrookfly_butterrook3 = "butterflyrookfly/butterrook3";
		public const string Butterflyrookfly_butterrook4 = "butterflyrookfly/butterrook4";
		public const string Butterflyrookfly_butterrook5 = "butterflyrookfly/butterrook5";
		public const string Butterflyrookfly_butterrook6 = "butterflyrookfly/butterrook6";
		public const string Butterflyrookfly_butterrook7 = "butterflyrookfly/butterrook7";
		public const string Butterflyrookfly_butterrook8 = "butterflyrookfly/butterrook8";
		public const string Butterflyrookfly_butterrook9 = "butterflyrookfly/butterrook9";
		public const string Butterflyrookfly_butterrooko14 = "butterflyrookfly/butterrooko14";
	}
}